project:
  type: website
  render:
    - "*.qmd"
    - "!blog/"

website:
  title: "blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  repo-url: https://github.com/adidenkova/blog
  repo-actions: [source]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
